name: Deploy to Hugging Face

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Hugging Face Restart
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.HF_TOKEN }}" \
          "https://huggingface.co/api/spaces/sudharshan59/crop-disease-ai/restart"
